"""update tables

Revision ID: 2dfaa7685987
Revises: 
Create Date: 2024-05-13 10:17:51.907112

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2dfaa7685987'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intensitylevel',
    sa.Column('intensity_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('intensity_id')
    )
    op.create_table('musclegroup',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('goal',
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('goal_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('goal_id')
    )
    op.create_table('workout',
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('muscle_group_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.equipment_id'], ),
    sa.ForeignKeyConstraint(['muscle_group_id'], ['musclegroup.group_id'], ),
    sa.PrimaryKeyConstraint('workout_id')
    )
    op.drop_table('goals')
    op.drop_table('muscle_groups')
    op.drop_table('workouts')
    op.drop_table('intensity_levels')
    op.alter_column('equipment', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False)
    op.alter_column('progress', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('progress', 'workout_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('progress', 'date_completed',
               existing_type=sa.DATE(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.drop_constraint('progress_workout_id_fkey', 'progress', type_='foreignkey')
    op.create_foreign_key(None, 'progress', 'workout', ['workout_id'], ['workout_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'progress', type_='foreignkey')
    op.create_foreign_key('progress_workout_id_fkey', 'progress', 'workouts', ['workout_id'], ['workout_id'])
    op.alter_column('progress', 'date_completed',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('progress', 'workout_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('progress', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('equipment', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               nullable=True)
    op.create_table('intensity_levels',
    sa.Column('intensity_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('intensity_id', name='intensity_levels_pkey')
    )
    op.create_table('workouts',
    sa.Column('workout_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('muscle_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('equipment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.equipment_id'], name='workouts_equipment_id_fkey'),
    sa.ForeignKeyConstraint(['muscle_group_id'], ['muscle_groups.group_id'], name='workouts_muscle_group_id_fkey'),
    sa.PrimaryKeyConstraint('workout_id', name='workouts_pkey')
    )
    op.create_table('muscle_groups',
    sa.Column('group_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('group_id', name='muscle_groups_pkey')
    )
    op.create_table('goals',
    sa.Column('goal_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('goal_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='goals_user_id_fkey'),
    sa.PrimaryKeyConstraint('goal_id', name='goals_pkey')
    )
    op.drop_table('workout')
    op.drop_table('goal')
    op.drop_table('musclegroup')
    op.drop_table('intensitylevel')
    # ### end Alembic commands ###
