"""Remove autoincrement from primary keys

Revision ID: d1a18058a94b
Revises: 0b36c83606e1
Create Date: 2024-05-15 15:32:32.574735

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd1a18058a94b'
down_revision: str | None = '0b36c83606e1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workouts', 'reps',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workouts', 'sets',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workouts', 'weights',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workouts', 'weights',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('workouts', 'sets',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('workouts', 'reps',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
